services:

  messaging-comp-dev-redis:
    image: redis:5.0.5
    container_name: messaging-comp-dev-redis
    ports:
      - "6379:6379"
    networks:
      - common-messaging-dev-network

  messaging-comp-dev-rabbitmq:
    image: rabbitmq:3.7.17-management
    container_name: messaging-comp-dev-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - common-messaging-dev-network

#$ docker run -d --hostname my-rabbit --name some-rabbit -e RABBITMQ_DEFAULT_USER=user -e RABBITMQ_DEFAULT_PASS=password rabbitmq:3-management


networks:
  common-messaging-dev-network:
    driver: bridge